import type { DropdownOption, DropdownProps } from './Dropdown';

export const dropdownOptionSets = {
  BusinessTypes: [
    { label: 'Retail Store Owner', value: 'retail-store-owner' },
    { label: 'Convenience Shop', value: 'convenience-shop' },
    { label: 'Hospitality', value: 'hospitality' },
    { label: 'Catering & Events', value: 'catering-events' },
    { label: 'Online/Delivery Only', value: 'online-delivery-only' },
    { label: 'Restaurant / Café', value: 'restaurant-cafe' },
    { label: 'Bar / Pub', value: 'bar-pub' },
    { label: 'Bakery / Pastry Shop', value: 'bakery-pastry' },
    { label: 'Food Truck / Mobile Vendor', value: 'food-truck-mobile' },
    { label: 'Grocery / Supermarket', value: 'grocery-supermarket' },
    { label: 'Butcher / Fishmonger', value: 'butcher-fishmonger' },
    { label: 'Delicatessen', value: 'delicatessen' },
    { label: 'Coffee Roaster', value: 'coffee-roaster' },
    { label: 'Winery / Brewery / Distillery', value: 'winery-brewery-distillery' },
    { label: 'Farm / Producer', value: 'farm-producer' },
    { label: 'Wholesale / Distributor', value: 'wholesale-distributor' },
    { label: 'Corporate Catering', value: 'corporate-catering' },
    { label: 'Education (School / University)', value: 'education' },
    { label: 'Healthcare (Hospital / Care Home)', value: 'healthcare' },
    { label: 'Office / Workplace Canteen', value: 'workplace-canteen' },
    { label: 'Community / Non-profit', value: 'community-nonprofit' },
    { label: 'Pop-up / Market Stall', value: 'popup-market-stall' },
    { label: 'Other', value: 'other' },
  ],
  Roles: [
    { label: 'Viewer', value: 'viewer' },
    { label: 'Editor', value: 'editor' },
    { label: 'Admin', value: 'admin' },
  ],
} satisfies Record<string, DropdownOption[]>;

export const dropdownExamples = {
  Default: {
    label: 'Label',
    placeholder: 'Label',
    options: dropdownOptionSets.BusinessTypes,
    value: undefined,
    variant: 'default',
    showLeftIcon: true,
    required: true,
    requiredText: 'required',
  },
  Active: {
    label: 'Label',
    placeholder: 'Label',
    options: dropdownOptionSets.BusinessTypes,
    value: undefined,
    variant: 'focus',
    showLeftIcon: true,
    required: true,
    requiredText: 'required',
  },
  Filled: {
    label: 'Label',
    placeholder: 'Label',
    options: dropdownOptionSets.BusinessTypes,
    value: 'convenience-shop',
    variant: 'selected',
    showLeftIcon: true,
    required: true,
    requiredText: 'required',
  },
  Disabled: {
    label: 'Label',
    placeholder: 'Label',
    options: dropdownOptionSets.BusinessTypes,
    value: 'convenience-shop',
    variant: 'disabled',
    showLeftIcon: true,
    required: true,
    requiredText: 'required',
  },
  Opened: {
    label: 'Label',
    placeholder: 'Label',
    options: dropdownOptionSets.BusinessTypes,
    value: undefined,
    variant: 'default',
    open: true,
    showLeftIcon: true,
    required: true,
    requiredText: 'required',
  },
} satisfies Record<string, Partial<DropdownProps>>;


